
<option value="ACC">ACC (Bachelor of Science in Accountancy)</option>
<option value="ACT">ACT (Bachelor of Science in Accounting Technology)</option>
<option value="AGR">AGR (Bachelor of Science in Agroforestry)</option>
<option value="AIS">AIS (Bachelor of Science in Accounting Information System)</option>
<option value="ANT">ANT ()</option>
<option value="AR">AR (Bachelor of Science in Architecture)</option>
<option value="ATS">ATS ()</option>
<option value="BA">BA ()</option>
<option value="BCS">BCS ()</option>
<option value="BE">BE (Bachelor of Science in Business Administration- Business Economics)</option>
<option value="BEC">BEC (Bachelor of Early Childhood Education)</option>
<option value="BED">BED (Bachelor of Elementary Education - Generalist)</option>
<option value="BEE">BEE (ENGLISH (OLD))</option>
<option value="BIO">BIO (Bachelor of Science in Biology)</option>
<option value="BMMA">BMMA (Bachelor of Multimedia Arts)</option>
<option value="BP">BP (Bachelor of Science in Biology major in Plant Biology)</option>
<option value="BPE">BPE (Bachelor of Physical Education)</option>
<option value="BRC">BRC ()</option>
<option value="BS">BS (Bachelor of Secondary Education - General Science)</option>
<option value="BSED">BSED (OLD BSED)</option>
<option value="BSN">BSN (Bachelor of Science in Nursing)</option>
<option value="CE">CE (Bachelor of Science in Civil Engineering)</option>
<option value="CES">CES (Bachelor of Science in Civil Engineering - Structural)</option>
<option value="CGR">CGR ()</option>
<option value="CHE">CHE (Bachelor of Science in Chemical Engineering)</option>
<option value="COE">COE (Bachelor of Science in Computer Engineering)</option>
<option value="COM">COM (BA Communication)</option>
<option value="CpE">CpE (Bachelor of Science in Computer Engineering)</option>
<option value="CRI">CRI (Bachelor of Science in Criminology)</option>
<option value="CSC">CSC (Bachelor of Science in Computer Science)</option>
<option value="DAL">DAL ()</option>
<option value="DAT">DAT (Bachelor of Science in Entertainment and Multimedia Computing - Digital Animation Technology)</option>
<option value="DBA">DBA ()</option>
<option value="DPA">DPA ()</option>
<option value="DPE">DPE ()</option>
<option value="DPF">DPF ()</option>
<option value="DPM">DPM ()</option>
<option value="DSD">DSD ()</option>
<option value="ECE">ECE (Bachelor of Science in Electronics Engineering)</option>
<option value="EDD">EDD ()</option>
<option value="EE">EE (Bachelor of Science in Electrical Engineering)</option>
<option value="EED">EED ()</option>
<option value="EIM">EIM ()</option>
<option value="ELM">ELM (Elementary)</option>
<option value="EM">EM ()</option>
<option value="ENG">ENG (AB English)</option>
<option value="ENR">ENR (Bachelor of Science in Environmental Science)</option>
<option value="ENT">ENT (Bachelor of Science in Entrepreneurship)</option>
<option value="EP">EP ()</option>
<option value="EPS">EPS ()</option>
<option value="EST">EST (Bachelor of Special Education - Elementary School Teaching)</option>
<option value="FA">FA (Bachelor of Fine Arts and Design)</option>
<option value="FIL">FIL (Bachelor of Secondary Education - Filipino)</option>
<option value="FIN">FIN ()</option>
<option value="FM">FM (Bachelor of Science in Business Administration- Financial Management)</option>
<option value="FOR">FOR (Bachelor of Science in Forestry)</option>
<option value="GC">GC ()</option>
<option value="GD">GD (Bachelor of Science in Entertainment and Multimedia Computing - Game Development)</option>
<option value="GEN">GEN (OLD GENERALIST)</option>
<option value="GEO">GEO (Bachelor of Science in Civil Engineering - Geotechnical)</option>
<option value="GS">GS (Master of Science in Socialwork)</option>
<option value="HM">HM (Bachelor of Science in Hotel and Restaurant Management)</option>
<option value="HR">HR (Bachelor of Science in Business Administration- Human Resource Management)</option>
<option value="HRM">HRM (Bachelor of Science in Hotel and Restaurant Management)</option>
<option value="IA">IA (Bachelor of Science in Internal Auditing)</option>
<option value="IS">IS (Bachelor of Science in Information Systems)</option>
<option value="ISM">ISM ()</option>
<option value="IT">IT (Bachelor of Science in Information Technology)</option>
<option value="JD">JD ()</option>
<option value="JRN">JRN ()</option>
<option value="LIS">LIS (Bachelor of Science in Library and Information Science)</option>
<option value="LLB">LLB ()</option>
<option value="LM">LM (Bachelor of Science in Legal Management)</option>
<option value="LS">LS ()</option>
<option value="LST">LST ()</option>
<option value="MA">MA (Bachelor of Multimedia Arts)</option>
<option value="MAC">MAC ()</option>
<option value="MAE">MAE ()</option>
<option value="MBA">MBA (Master in Business Administration)</option>
<option value="MC">MC (Bachelor of Arts in Mass Communication)</option>
<option value="MCE">MCE ()</option>
<option value="MCH">MCH ()</option>
<option value="MCJ">MCJ ()</option>
<option value="MCR">MCR ()</option>
<option value="ME">ME (Bachelor of Science in Mechanical Engineering)</option>
<option value="MEC">MEC ()</option>
<option value="MED">MED ()</option>
<option value="MEE">MEE ()</option>
<option value="MEP">MEP ()</option>
<option value="MIH">MIH ()</option>
<option value="MIS">MIS ()</option>
<option value="MIT">MIT ()</option>
<option value="MKG">MKG ()</option>
<option value="MLS">MLS ()</option>
<option value="MM">MM (Bachelor of Science in Business Administration- Marketing Management)</option>
<option value="MMD">MMD ()</option>
<option value="MME">MME ()</option>
<option value="MMH">MMH ()</option>
<option value="MMK">MMK ()</option>
<option value="MPA">MPA ()</option>
<option value="MSA">MSA ()</option>
<option value="MSC">MSC ()</option>
<option value="MSD">MSD ()</option>
<option value="MSE">MSE ()</option>
<option value="MSI">MSI ()</option>
<option value="MSM">MSM ()</option>
<option value="MSP">MSP ()</option>
<option value="MST">MST ()</option>
<option value="MSW">MSW (Master of Science in Socialwork)</option>
<option value="MT">MT (Bachelor of Science in Medical Technology/Medical Laboratory Scienc)</option>
<option value="MTH">MTH (Bachelor of Science in Mathematics)</option>
<option value="NAD">NAD (Bachelor of Science in Nutrition and Dietetics)</option>
<option value="PAM">PAM ()</option>
<option value="PDC">PDC ()</option>
<option value="PDM">PDM ()</option>
<option value="PE">PE ()</option>
<option value="PHM">PHM (OLD PE)</option>
<option value="PHR">PHR (Bachelor of Science in Pharmacy)</option>
<option value="PIL">PIL ()</option>
<option value="PRE">PRE (OLD PRESCHOOL)</option>
<option value="PS">PS (PhD in social development)</option>
<option value="PSY">PSY (Bachelor of Science in Psychology)</option>
<option value="REM">REM (Bachelor of Science in Real Estate Management)</option>
<option value="SCI">SCI (OLD SCIENCE)</option>
<option value="SOC">SOC ()</option>
<option value="SPD">SPD (OLD Special Education)</option>
<option value="SPE">SPE (OLD Physical Education)</option>
<option value="SST">SST (Bachelor of Secondary Education-Social Studies)</option>
<option value="SW">SW (Bachelor of Science in Social Work)</option>
<option value="SWN">SWN (Master of Science in Social Work)</option>
<option value="SWV">SWV (Master of Science in Social Work)</option>
<option value="TLE">TLE ()</option>
<option value="TM">TM (Bachelor of Science in Tourism Management)</option>
<option value="TR">TR (Bachelor of Science in Civil Engineering - Transportation)</option>
<option value="URP">URP ()</option>
<option value="WR">WR (Bachelor of Science in Civil Engineering - Water Resource)</option>